name: rive_examples
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/rive_examples/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  assets:
    - assets/rive/

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  faker:
  flare_flutter:
  flutter_workbench:
    git:
      url: https://github.com/tmcmaster/flutter_workbench.git